In [ ]:
pip install "pymongo[srv]"

In [ ]:
pip install sqlalchemy

In [ ]:
pip install mysqlclient

In [4]:
import sqlalchemy as db # librearias para trabajar
from sqlalchemy import text
import pandas as pd

In [5]:
engine = db.create_engine("mysql://root:root@127.0.0.1:3310/retail_db") # nosconetamos a la base de datos 
conn = engine.connect()

In [ ]:
customers_df = pd.read_sql_query('select * from customers', con=conn) # leemos la base de datos y traemos la tabla customers
customers_df

In [ ]:
customers_df_2 = pd.read_sql_table('categories', engine) # leer una tabla de la base de datos de otra forma 
customers_df_2

In [15]:
from pymongo import MongoClient # nos conectamso a la base de datos de mongodb
conn_string = "mongodb+srv://luimarper045:MI4bT76eB6lOOlIs@cluster0.hjxcd.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0"
client = MongoClient(conn_string)

client['bd_test']

Database(MongoClient(host=['cluster0-shard-00-01.hjxcd.mongodb.net:27017', 'cluster0-shard-00-00.hjxcd.mongodb.net:27017', 'cluster0-shard-00-02.hjxcd.mongodb.net:27017'], document_class=dict, tz_aware=False, connect=True, retrywrites=True, w='majority', appname='Cluster0', authsource='admin', replicaset='atlas-1zltow-shard-0', tls=True), 'bd_test')

In [13]:
coleccion = client['bd_test']['tabla']
df = coleccion.find({})
df

In [16]:
coleccion = client['sample_mflix']['embedded_movies'] # colocamos base de datos y tabla de mongo db
cursor_mongo = coleccion.find({})

df = pd.DataFrame(cursor_mongo)
df

,_id,plot,genres,runtime,rated,cast,num_mflix_comments,title,fullplot,languages,...,awards,lastupdated,year,imdb,countries,type,tomatoes,plot_embedding,poster,metacritic
0,573a1391f29313caabcd93a3,Navy divers clear the torpedo tube of a sunken...,"[Action, Drama]",77.0,PASSED,"[Kenneth MacKenna, Frank Albertson, J. Farrell...",1,Men Without Women,Aboard the U.S. submarine S13 in the China sea...,[English],...,"{'wins': 1, 'nominations': 0, 'text': '1 win.'}",2015-08-31 00:25:42.873000000,1930,"{'rating': 5.8, 'votes': 154, 'id': 21140}",[USA],movie,"{'viewer': {'rating': 3.3, 'numReviews': 84, '...","[0.01020927, -0.011224265, 0.015686288, -0.018...",NaN,NaN
1,573a1391f29313caabcd8319,An irresponsible young millionaire changes his...,"[Action, Comedy, Romance]",58.0,PASSED,"[Harold Lloyd, Jobyna Ralston, Noah Young, Jim...",0,For Heaven's Sake,"The Uptown Boy, J. Harold Manners (Lloyd) is a...",[English],...,"{'wins': 0, 'nominations': 1, 'text': '1 nomin...",2015-08-19 00:35:01.953000000,1926,"{'rating': 7.6, 'votes': 918, 'id': 16895}",[USA],movie,"{'viewer': {'rating': 3.6, 'numReviews': 87, '...","[-0.0059373598, -0.026604708, -0.0070914757, -...",https://m.media-amazon.com/images/M/MV5BMTcxMT...,NaN
2,573a1392f29313caabcd9ca6,An ambitious and near insanely violent gangste...,"[Action, Crime, Drama]",93.0,PASSED,"[Paul Muni, Ann Dvorak, Karen Morley, Osgood P...",1,Scarface,Johnny Lovo rises to the head of the bootleggi...,[English],...,"{'wins': 2, 'nominations': 0, 'text': '2 wins.'}",2015-09-03 00:32:16.227000000,1932,"{'rating': 7.8, 'votes': 18334, 'id': 23427}",[USA],movie,"{'viewer': {'rating': 3.9, 'numReviews': 25579...","[-0.015579718, -0.03428319, 0.015228297, -0.04...",https://m.media-amazon.com/images/M/MV5BYmMxZT...,NaN
3,573a1392f29313caabcdac22,A major countermands orders and attacks to rev...,"[Action, Adventure, Romance]",115.0,APPROVED,"[Errol Flynn, Olivia de Havilland, Patric Know...",0,The Charge of the Light Brigade,Major Vickers is an officer at the 27th Lancer...,[English],...,"{'wins': 0, 'nominations': 4, 'text': 'Won 1 O...",2015-08-20 00:35:09.343000000,1936,"{'rating': 7.1, 'votes': 3187, 'id': 27438}",[USA],movie,"{'viewer': {'rating': 3.5, 'numReviews': 730, ...","[-0.032960705, -0.02468733, -0.018857453, -0.0...",https://m.media-amazon.com/images/M/MV5BNmUzYj...,NaN
4,573a1390f29313caabcd5293,Young Pauline is left a lot of money when her ...,[Action],199.0,NaN,"[Pearl White, Crane Wilbur, Paul Panzer, Edwar...",0,The Perils of Pauline,Young Pauline is left a lot of money when her ...,[English],...,"{'wins': 1, 'nominations': 0, 'text': '1 win.'}",2015-09-12 00:01:18.647000000,1914,"{'rating': 7.6, 'votes': 744, 'id': 4465}",[USA],movie,"{'viewer': {'rating': 2.8, 'numReviews': 9}, '...","[0.00072939653, -0.026834568, 0.013515796, -0....",https://m.media-amazon.com/images/M/MV5BMzgxOD...,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3478,573a13f3f29313caabddfde0,Two siblings discover a supernatural escape fr...,"[Drama, Fantasy, Thriller]",90.0,NaN,"[Kiernan Shipka, Timothèe Chalamet, Elizabeth ...",0,One and Two,Zac and Eva live with their parents in isolate...,[English],...,"{'wins': 0, 'nominations': 1, 'text': '1 nomin...",2015-09-04 00:10:45.303000000,2015,"{'rating': 5.5, 'votes': 261, 'id': 3975510}",[USA],movie,NaN,"[0.01443591, -0.014968648, -0.0077961707, -0.0...",https://m.media-amazon.com/images/M/MV5BMDkyNW...,47.0
3479,573a13e2f29313caabdbf161,Inspector Richard Kemp never got around to put...,"[Crime, Fantasy, Thriller]",102.0,NaN,"[Jean-Hugues Anglade, Mèlanie Thierry, Philipp...",0,L'autre vie de Richard Kemp,Inspector Richard Kemp never got around to put...,[French],...,"{'wins': 0, 'nominations': 2, 'text': '2 nomin...",2015-08-21 00:48:07.127000000,2013,"{'rating': 6.5, 'votes': 578, 'id': 2843344}",[France],movie,"{'viewer': {'rating': 3.7, 'numReviews': 19}, ...","[-0.009451801, 0.0073785027, 0.0007042269, -0....",https://m.media-amazon.com/images/M/MV5BMjI3MD...,NaN
3480,573a13edf29313caabdd3a09,A 74-year-old widow realizes she is becoming a...,"[Comedy, Fantasy, Music]",124.0,NaN,"[Eun-kyung Shim, Mun-hee Na, In-hwan Park, Don...",1,Miss Granny,A 74-year-old widow realizes she is becoming a...,[Korean],...,"{'wins': 2, 'nominations': 8, 'text': '2 wins ...",2015-08-20 00:41:44.470000000,2014,"{'rating': 7.3, 'votes': 1076, 'id': 3516378}",[South Korea],movie,NaN,"[0.0011758477, -0.02316831, 0.020655451, -0.00...",https://m.media-amazon.com/images/M/MV5BMWMzNT...,NaN
3481,573a13eef29313caabdd6ff4,A struggling writer meets death and falls in l...,"[Drama, Fantasy, Romance]",93.0,NaN,"[Dylan Taylor, Melanie Scrofano, Meghan Heffer...",0,A Sunday Kind of Love,A struggling writer meets death and falls in l...,[English],...,"{'wins': 0, 'nominations': 1, 'text': '1 nomin...",2015-09-11 00:04:53.430000000,2015,"{'rating': '', 'votes': '', 'id': 3611112}",[Canada],movie,NaN,"[0.007919935, -0.014139471, -8.491776e-05, -0....",https://m.media-amazon.com/images/M/MV5BMTQ1MT...,NaN
3482,573a13f7f29313caabde65b4,Our figurine sized supermen hero embarks on an...,"[Adventure, Fantasy, Mystery]",68.0,NaN,"[Daniel Tadesse, Selam Tesfayie]",0,Crumbs,Crumbs is a Spanish-Ethiopian Since fictional ...,"[Amharic, Afrikaans]",...,"{'wins': 2, 'nominations': 5, 'text': '2 wins ...",2015-09-06 00:05:01.353000000,2015,"{'rating': 6.1, 'votes': 81, 'id': 4362764}","[Ethiopia, Spain, Finland]",movie,NaN,"[-0.0009377669, -0.021177763, -0.0052474686, -...",NaN,NaN